---
apiVersion: v1
kind: Namespace
metadata:
  name: covenant-finances
  labels:
    name: covenant-finances

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covenant-finances
  namespace: covenant-finances
  labels:
    app: covenant-finances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covenant-finances
  template:
    metadata:
      labels:
        app: covenant-finances
        # Change below when you want to force a new remote build
        # git rev-parse HEAD
        latest_commit_sha: 77a4d8d11b25dace8f3657c0b8552d91f1209fdb
    spec:
      containers:
        - name: covenant-finances-app
          image: us-central1-docker.pkg.dev/covenant-finances/covenant-finances-images/cluster-db1:latest
          ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: covenant-finances-loadbalancer
  namespace: covenant-finances
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: covenant-finances
  type: LoadBalancer
  loadBalancerIP: "34.67.225.120"
