# from https://thedatabaseme.de/2022/03/13/keep-the-elefants-in-line-deploy-zalando-operator-on-your-kubernetes-cluster/
kind: Namespace
apiVersion: v1
metadata:
  name: postgres

---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  teamId: "postgres"
  volume:
    size: 2Gi
  numberOfInstances: 2
  users:
    finance_owner:  # database owner
    - superuser
    - createdb
  databases:
    finance: finance_owner # dbname: owner
  preparedDatabases:
    finance: {}
  postgresql:
    version: "14"

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-dns
  namespace: postgres
spec:
  clusterIP: 34.118.230.250
  ports:
  - name: psql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    application: spilo
  type: ClusterIP
